name: Tests
  
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  macos:
    name: macOS 10.15 tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: SPM tests
        run: make test platform=macos
      - name: Normalize coverage info
        run: xcrun llvm-cov export -format lcov .build/debug/swift-sassPackageTests.xctest/Contents/MacOS/swift-sassPackageTests -instr-profile .build/debug/codecov/default.profdata -ignore-filename-regex "(Test|checkouts|pb\.swift$)" > coverage.lcov
      - name: Upload coverage
        run: bash <(curl -s https://codecov.io/bash) -f coverage.lcov

  linux:
    name: Linux SPM unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: make test platform=linux

  macos11:
    name: macOS 11 tests
    runs-on: macos-11.0
    steps:
      - uses: actions/checkout@v2
      - name: Xcode
        run: sudo xcode-select -s /Applications/Xcode_12.2.app/Contents/Developer
      - name: SPM tests
        run: make test platform=macos
