name: Tests
  
on:
  push:
  pull_request:

jobs:
  macos:
    name: macOS tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: SPM tests
        run: make test platform=macos
      - name: Normalize coverage info
        run: xcrun llvm-cov export -format lcov .build/debug/swift-sassPackageTests.xctest/Contents/MacOS/swift-sassPackageTests -instr-profile .build/debug/codecov/default.profdata -ignore-filename-regex Test > coverage.lcov
      - name: Upload coverage
        run: bash <(curl -s https://codecov.io/bash) -f coverage.lcov

  linux:
    name: Linux SPM unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run tests
        run: make test platform=linux
