name: Tests
  
on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']

jobs:
  macos11:
    name: macOS 11 tests
    runs-on: macos-11.0
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.5.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            .build
            Tests/EmbeddedSassTests/dart-sass-embedded
          key: ${{ runner.os }}-spm4-${{ hashFiles('Package.resolved', 'Makefile') }}

      - name: SPM tests
        run: |
          make libsass4
          make test
      - name: Normalize coverage info
        run: xcrun llvm-cov export -format lcov .build/debug/swift-sassPackageTests.xctest/Contents/MacOS/swift-sassPackageTests -instr-profile .build/debug/codecov/default.profdata -ignore-filename-regex "(Test|checkouts|pb\.swift$)" > coverage.lcov
      - name: Upload coverage
        run: bash <(curl -s https://codecov.io/bash) -f coverage.lcov
